# v2 syntax
version: '2'

# Named volumes
volumes:
  # Redis Data
  portals-redis-data:
    driver: local
  # Minio Data
  portals-minio-data:
    driver: local

services:
  # Redis
  cache:
    image: redis:4.0
    container_name: portals-redis
    command: --appendonly yes
    volumes:
      - portals-redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"

  # Mailhog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: portals-mailhog
    ports:
      - "1025:1025"
      - "${MAILHOG_PORT}:8025"

  # PHP (with Apache)
  web:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: portals-web
    volumes:
      - ./desenv:/var/www/html/
      - ./infra/vhost:/etc/nginx/conf.d/
    ports:
      - "${NGINX_HTTP_PORT}:80"
    links:
      - cache
      - mailhog

